name: Demo

on:
  push:
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  demo:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2021.12.16'

      - uses: actions/checkout@v2

      - name: Run on Ubuntu
        run: clj-kondo --lint deps.edn --config '{:output {:pattern "::{{level}} file={{filename}},line={{row}},col={{col}}::{{message}}"}}'


